server:
  port: 8980
logging:
  level: DEBUG
  level.org.springframework.web: DEBUG
  level.org.hibernate: ERROR
  file:
    name: 'LOGS/dev_app.log'
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
telegram:
  bot:
    token: 2129557551:AAFNe5JdnKsA0f6l_J3IkSdFxPnqTLVVDEU
    username: new1KUsersBot
spring:
  datasource:
    username: BD_Telegram
    password: "!QAZzaq1"
    url: jdbc:sqlserver://server:1433;databaseName=telegram_weatherGPT_bot;encrypt=true;trustServerCertificate=true
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: create
#      ddl-auto: update
    show-sql: false
GPT:
  GPTYa:
    url: https://llm.api.cloud.yandex.net/foundationModels/v1/completion
    token: AQVNwAzlqRiaImIvA706MvvN94EszdT92lW8JvIv
    stream: false
    maxToken: 150
    temperature: 0.8
    model: yandexgpt-lite
weather:
  url: http://api.weatherapi.com/v1/current.json
  token: ad2a2951d9334d8490980824240601
  lang: ru