package com.app.weatherGPT.dto;    /*
 *created by WerWolfe on Lang
 */

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum Lang {

    AF("Afrikaans"),
    AM("አማርኛ"),
    AR("العربية"),
    ARN("Mapudungun"),
    AS("অসমীয়া"),
    AZ("Azərbaycanlı"),
    BA("Башҡорт"),
    BE("беларуская"),
    BG("български"),
    BN("বাংলা"),
    BO("བོད་ཡིག"),
    BR("brezhoneg"),
    BS("bosanski/босански"),
    CA("català"),
    CO("Corsu"),
    CS("čeština"),
    CY("Cymraeg"),
    DA("dansk"),
    DE("Deutsch"),
    DSB("dolnoserbšćina"),
    DV("ދިވެހިބަސް"),
    EL("ελληνικά"),
    EN("English"),
    ES("español"),
    ET("eesti"),
    EU("euskara"),
    FA("فارسى"),
    FI("suomi"),
    FIL("Filipino"),
    FO("føroyskt"),
    FR("français"),
    FY("Frysk"),
    GA("Gaeilge"),
    GD("Gàidhlig"),
    GL("galego"),
    GSW("Schweizerdeutsch"),
    GU("ગુજરાતી"),
    HA("Hausa"),
    HE("עברית"),
    HI("हिंदी"),
    HR("hrvatski"),
    HSB("hornjoserbšćina"),
    HU("magyar"),
    HY("Հայերեն"),
    ID("Bahasa Indonesia"),
    IG("Igbo"),
    II("ꆈꌠꁱꂷ"),
    IS("íslenska"),
    IT("italiano"),
    IU("Inuktitut /ᐃᓄᒃᑎᑐᑦ (ᑲᓇᑕ)"),
    JA("日本語"),
    KA("ქართული"),
    KK("Қазақша"),
    KL("kalaallisut"),
    KM("ខ្មែរ"),
    KN("ಕನ್ನಡ"),
    KO("한국어"),
    KOK("कोंकणी"),
    CKB("کوردی"),
    KY("Кыргыз"),
    LB("Lëtzebuergesch"),
    LO("ລາວ"),
    LT("lietuvių"),
    LV("latviešu"),
    MI("Reo Māori"),
    MK("македонски јазик"),
    ML("മലയാളം"),
    MN("Монгол хэл/ᠮᠤᠨᠭᠭᠤᠯ ᠬᠡᠯᠡ"),
    MOH("Kanien'kéha"),
    MR("मराठी"),
    MS("Bahasa Malaysia"),
    MT("Malti"),
    MY("Myanmar"),
    NB("norsk (bokmål)"),
    NE("नेपाली (नेपाल)"),
    NL("Nederlands"),
    NN("norsk (nynorsk)"),
    NO("norsk"),
    ST("Sesotho sa Leboa"),
    OC("Occitan"),
    OR("ଓଡ଼ିଆ"),
    PA("ਪੰਜਾਬੀ"),
    PL("polski"),
    PRS("درى"),
    PS("پښتو"),
    PT("Português"),
    QUC("K'iche"),
    QU("runasimi"),
    RM("Rumantsch"),
    RO("română"),
    RU("русский"),
    RW("Kinyarwanda"),
    SA("संस्कृत"),
    SAH("саха"),
    SE("davvisámegiella"),
    SI("සිංහල"),
    SK("slovenčina"),
    SL("slovenski"),
    SMA("åarjelsaemiengiele"),
    SMJ("julevusámegiella"),
    SMN("sämikielâ"),
    SMS("sääm´ǩiõll"),
    SQ("shqipe"),
    SR("srpski/српски"),
    SV("svenska"),
    SW("Kiswahili"),
    SYC("ܣܘܪܝܝܐ"),
    TA("தமிழ்"),
    TE("తెలుగు"),
    TG("Тоҷикӣ"),
    TH("ไทย"),
    TK("türkmençe"),
    TN("Setswana"),
    TR("Türkçe"),
    TT("Татарча"),
    TZM("Tamazight"),
    UG("ئۇيغۇرچە"),
    UK("українська"),
    UR("اُردو"),
    UZ("U'zbek/Ўзбек"),
    VI("Tiếng Việt"),
    WO("Wolof"),
    XH("isiXhosa"),
    YO("Yoruba"),
    ZH("中文"),
    ZU("isiZulu");

    private final String label;

    @Override
    public String toString() {
        return getLabel();
    }
}
